/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(information)'}/about` | `/about`; params?: Router.UnknownInputParams; } | { pathname: `${'/(information)'}/contact` | `/contact`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/exercises` | `/exercises`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/exercise_3`; params?: Router.UnknownInputParams; } | { pathname: `/exercise_4`; params?: Router.UnknownInputParams; } | { pathname: `/exercise_4/useEffect/useEffect`; params?: Router.UnknownInputParams; } | { pathname: `/exercise_4/useState/state`; params?: Router.UnknownInputParams; } | { pathname: `/exercise_5`; params?: Router.UnknownInputParams; } | { pathname: `/exercise_6`; params?: Router.UnknownInputParams; } | { pathname: `/exercise_7`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/settings/Test1`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(information)'}/about` | `/about`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(information)'}/contact` | `/contact`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/exercises` | `/exercises`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/exercise_3`; params?: Router.UnknownOutputParams; } | { pathname: `/exercise_4`; params?: Router.UnknownOutputParams; } | { pathname: `/exercise_4/useEffect/useEffect`; params?: Router.UnknownOutputParams; } | { pathname: `/exercise_4/useState/state`; params?: Router.UnknownOutputParams; } | { pathname: `/exercise_5`; params?: Router.UnknownOutputParams; } | { pathname: `/exercise_6`; params?: Router.UnknownOutputParams; } | { pathname: `/exercise_7`; params?: Router.UnknownOutputParams; } | { pathname: `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/settings/Test1`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(information)'}/about${`?${string}` | `#${string}` | ''}` | `/about${`?${string}` | `#${string}` | ''}` | `${'/(information)'}/contact${`?${string}` | `#${string}` | ''}` | `/contact${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/exercises${`?${string}` | `#${string}` | ''}` | `/exercises${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/exercise_3${`?${string}` | `#${string}` | ''}` | `/exercise_4${`?${string}` | `#${string}` | ''}` | `/exercise_4/useEffect/useEffect${`?${string}` | `#${string}` | ''}` | `/exercise_4/useState/state${`?${string}` | `#${string}` | ''}` | `/exercise_5${`?${string}` | `#${string}` | ''}` | `/exercise_6${`?${string}` | `#${string}` | ''}` | `/exercise_7${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `/settings/Test1${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(information)'}/about` | `/about`; params?: Router.UnknownInputParams; } | { pathname: `${'/(information)'}/contact` | `/contact`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/exercises` | `/exercises`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/exercise_3`; params?: Router.UnknownInputParams; } | { pathname: `/exercise_4`; params?: Router.UnknownInputParams; } | { pathname: `/exercise_4/useEffect/useEffect`; params?: Router.UnknownInputParams; } | { pathname: `/exercise_4/useState/state`; params?: Router.UnknownInputParams; } | { pathname: `/exercise_5`; params?: Router.UnknownInputParams; } | { pathname: `/exercise_6`; params?: Router.UnknownInputParams; } | { pathname: `/exercise_7`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/settings/Test1`; params?: Router.UnknownInputParams; };
    }
  }
}
